### ISSUE TITLE
cffi not in rquirements list

### ISSUE THREAD

**Issue by schlowm0** [project-rig/rig_c_sa#6]
Please add the cffi package in the req list to not get the following error message:

Collecting rig_c_sa
  Downloading rig_c_sa-0.4.0.tar.gz
    Complete output from command python setup.py egg_info:
    c/_cffi_backend.c:15:17: fatal error: ffi.h: No such file or directory
    compilation terminated.
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-build-UU_GqE/rig-c-sa/setup.py", line 49, in <module>
        install_requires=["cffi>=1.0.0"],
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/dist.py", line 315, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/dist.py", line 361, in fetch_build_eggs
        replace_conflicting=True,
      File "/home/moritz/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 851, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/home/moritz/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1123, in best_match
        return self.obtain(req, installer)
      File "/home/moritz/.local/lib/python2.7/site-packages/pkg_resources/**init**.py", line 1135, in obtain
        return installer(requirement)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/dist.py", line 429, in fetch_build_egg
        return cmd.easy_install(req)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 665, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 695, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 876, in install_eggs
        return self.build_and_install(setup_script, setup_base)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1115, in build_and_install
        self.run_setup(setup_script, setup_base, args)
      File "/home/moritz/.local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 1103, in run_setup
        raise DistutilsError("Setup script exited with %s" % (v.args[0],))
    distutils.errors.DistutilsError: Setup script exited with error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by mundya** [comment]
Hi, "cffi" is in the list of required modules, can you check that you have libffi or similar installed?

**Comment by mundya** [comment]
You may also need something like libffi-dev.

**Comment by schlowm0** [comment]
I just had to manually install cfffi (pip install cffi) and after that I 
could install rig_c_sa (sudo pip install rig_c_sa) without any errors

**Comment by mundya** [comment]
OK, could you let me know what distribution you're using them I can have a look? Thanks

**Comment by schlowm0** [comment]
I am operating Ubuntu Gnome 16.04

**Comment by mundya** [comment]
Thank you :)
